### PR TITLE
feature: add the Robinson model

### PR DESCRIPTION
**Pull request by tmorshed**
**Two steps already done:**
- [x] Add the model
- [x] Add an example for the model

**Next step:**
- [ ] Optimize and constrain the model

### CODE REVIEW

**Comment by tmorshed** [comment]
@JohnWangDataAnalyst This PR doesn't need to get merged just yet -- it's so that everyone can work on it together and document all the changes. All changes on `dev_CT` are reflected and discussed here, for the future when we will merge it to `dev` down the line.

**Comment by tmorshed** [comment]
Task for today, March 10: 
> - [ ] Optimize the model

**Comment by tmorshed** [comment]
Updates:
- Implemented global gain variable
- Changed some starting points
- Slightly improved the `modelfitting` module
- It doesn't explode (and return `nan`) anymore 

The average params over all regions looks like this
image
Monotonous changes -- no convergence.
`phi_dot` values go to non-expected values around 340,000

**Possible solution:**
- Setting boundaries for `phi` rates of change or the ratio of `phi` values in comparison to each other.

**Comment by tmorshed** [comment]
`docs` is failing too -- will check later

**Comment by tmorshed** [comment]
From other card:
> gain: exponential fitting nu_es
> 
> Image
> 
> 
> 
> Image
> 
> 
> 
> Image
> 
> 
> 
> Image
> 
>

**Comment by JohnGriffiths** [comment]
Related - issue #67

**Comment by JohnGriffiths** [comment]
Notes from discussion on this at dev meeting 2023-12-04:

- This PR will not get merged b/c it has jupyter notebooks in it, so a new PR will be needed that just has the code changes
- The code may be out of date as it was from a few months ago before major updates
- Need to know what the roadmap is for this robinson model time-domain implementation. @kevinkadak has indicated this is something he wants to look into, so he will take the lead on continuation of this issue
- Note that there is other work on linear analytic version of robinson model ( @sbastiaens , @tmorshed  , @JohnWangDataAnalyst  ) ; should run this and that work together as they are complementary
- Reference point for model behaviour should be nftsim
- Presumably kev wants to add plasticity equations to this eventually also?

**Pull request closed without merging**
